always-run:
  script: echo 'this should always run'
  tags:
    - k8s-root

on-pull-requests:
  script: echo 'this should run on pull requests'
  only:
    - external_pull_requests
  tags:
    - k8s-root
   
